config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get "dashboard/index"
    root "dashboard#index"

    resources :products
    resources :categories
    resources :pages, only: [:edit, :update]

    resources :orders, only: [:index] do
      member do
        patch :toggle_shipping
      end
    end
  end

  get "/about", to: "pages#about", as: :about
  get "/contact", to: "pages#contact", as: :contact
  post "/contact_submit", to: "pages#contact_submit", as: :contact_submit

  post "/create_checkout_session", to: "payments#create_checkout_session", as: :create_checkout_session
  get "/order_success", to: "payments#order_success", as: :order_success
  get "/order_cancel", to: "payments#order_cancel", as: :order_cancel

  root "products#index"

  resources :products, only: %i[index show]
  resources :orders, only: %i[new create show index]

  resource :cart, only: [:show] do
    post :add_item
    patch :update_item
    delete :remove_item
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-light">

  <!-- NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">

      <a class="navbar-brand" href="<%= admin_root_path %>">Admin Panel</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#adminNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="adminNav">

        <ul class="navbar-nav me-auto">

          <li class="nav-item"><%= link_to "Dashboard", admin_root_path, class: "nav-link" %></li>

          <li class="nav-item"><%= link_to "Products", admin_products_path, class: "nav-link" %></li>

          <li class="nav-item"><%= link_to "Categories", admin_categories_path, class: "nav-link" %></li>

          <li class="nav-item"><%= link_to "Orders", admin_orders_path, class: "nav-link" %></li>

          <li class="nav-item"><%= link_to "Edit About Page",
              edit_admin_page_path(Page.find_by(slug: "about")),
              class: "nav-link" %></li>

          <li class="nav-item"><%= link_to "Edit Contact Page",
              edit_admin_page_path(Page.find_by(slug: "contact")),
              class: "nav-link" %></li>
        </ul>

        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "Back to Store", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path,
                  method: :delete,
                  class: "btn btn-outline-light btn-sm ms-2",
                  form: { class: "d-inline" } %>
            </li>
        </ul>

      </div>

    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pixelforge Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
      rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>

  <!-- NAVBAR (Bootstrap) -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">

      <a class="navbar-brand" href="<%= root_path %>">PixelForge Store</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">

        <!-- LEFT SIDE NAV -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Cart (#{session[:cart]&.values&.sum || 0})", cart_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
      </ul>


        <!-- SEARCH BAR -->
        <%= form_with url: products_path, method: :get, local: true, class: "d-flex me-3" do %>

          <!-- Category filter -->
          <%= select_tag :category_id,
                options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
                include_blank: "All Categories",
                class: "form-select me-2" %>

          <!-- Search field -->
          <%= text_field_tag :q, params[:q], class: "form-control me-2", placeholder: "Search products..." %>

          <!-- Submit -->
          <%= submit_tag "Search", class: "btn btn-outline-info" %>

        <% end %>

        <!-- RIGHT SIDE NAV -->
        <ul class="navbar-nav ms-auto">

          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "My Orders", orders_path, class: "nav-link" %></li>


            <% if current_user.admin? %>
              <li class="nav-item"><%= link_to "Admin", admin_root_path, class: "nav-link text-info" %></li>
            <% end %>

            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path,
                    method: :delete,
                    class: "btn btn-outline-light btn-sm ms-2",
                    form: { class: "d-inline" } %>
            </li>

          <% else %>
            <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <% end %>

        </ul>

      </div>
    </div>
  </nav>

  <!-- Flash messages -->
  <div class="container">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
  </div>

  <!-- Main content -->
  <div class="container mb-5">
    <%= yield %>
  </div>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>